version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "@cap-js/attachments"
      - dependency-name: "@sap/cds"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
