name: Multi Tenancy Deploy

on:
  workflow_dispatch:
    inputs:
      space:
        description: 'CF Space to deploy'
        required: true
      sdm_branch:
        description: 'Branch to use for deployment'
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: dev
    env:
      CF_API: ${{ secrets.CF_API }}
      CF_USER: ${{ secrets.CF_USER }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_ORG: ${{ secrets.CF_ORG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sdm_branch }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Login to Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key \
          | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
          echo "deb https://packages.cloudfoundry.org/debian stable main" \
          | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt update
          sudo apt install cf8-cli
          cf login -a "$CF_API" -u "$CF_USER" -p "$CF_PASSWORD" -o "$CF_ORG" -s "${{ github.event.inputs.space }}"

      - name: Prepare app & Build and deploy
        run: |
          npm pack
          mv *.tgz app/multi-tenant/personal-space/cap-js-incidents-app/
          cd app/multi-tenant/personal-space/cap-js-incidents-app
          npm i *.tgz

      - name: Inject secrets into mta.yaml
        working-directory: app/multi-tenant/personal-space/cap-js-incidents-app
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          yq -i e '(.modules[] | select(.name == "incidents-mtx-srv")).properties.REPOSITORY_ID = "${{ secrets.REPOSITORY_ID_MT }}"' mta.yaml
          yq -i e '(.modules[] | select(.name == "incidents-mtx-mtx")).requires[] |= (select(.name == "app-api").properties.REPOSITORY_ID = "${{ secrets.REPOSITORY_ID_MT }}")' mta.yaml
          yq -i e '(.modules[] | select(.name == "incidents-mtx-mtx")).properties.DATABASE_ID = "${{ secrets.DATABASE_ID_MT }}"' mta.yaml

      - name: Build and deploy
        working-directory: app/multi-tenant/personal-space/cap-js-incidents-app
        run: |
          wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
          tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
          sudo mv mbt /usr/local/bin/
          npm i @sap/cds-dk -g
          mbt build
          cf install-plugin multiapps -f
          cf deploy mta_archives/capire.incidents.mtx_0.0.3.mtar -f
